# This is a basic workflow to help you get started with Actions

name: CI

permissions: write-all

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install skopeo
        run: |
          sudo apt-get -y update
          sudo apt-get -y install skopeo

      - name: List Windmill Tags
        run: |
          skopeo list-tags docker://ghcr.io/windmill-labs/windmill | tee windmill-tags.json
          
      - name: Git Commit Push Action
        # You may pin to the exact commit or the version.
        # uses: GuillaumeFalourd/git-commit-push@205c043bca2f932f7a48a28a8d619ba30eb84baf
        uses: GuillaumeFalourd/git-commit-push@v1.3
        with:
          # Commit message
          commit_message: Update windmill-tags.json # default is Commit performed using Push and Commit action
          # Branch to push the changes back to
          target_branch: master
          # Files to add separated by space
          files: .
