name: build

on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
      branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    packages: write

# ls Docker  | jq  --raw-input .  | jq --slurp .

jobs:
    pre:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Setup matrix
              run: |
                echo "docker_files=$(ls Docker  | jq  --raw-input .  | jq --slurp .)" >> "$GITHUB_ENV"
    
    test:
        needs: pre
        runs-on: ubuntu-latest
        strategy:
            # ↓ the real magic happens here - create dynamic matrix from the json
            matrix:
                docker_file: ${{ fromJson(env.docker_files) }}
        steps:
            - run: |
                echo ${{matrix.docker_file}}
