name: build

on:
    # Triggers the workflow on push or pull request events but only for the "master" branch
    push:
      branches: [ "master" ]
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

permissions:
    packages: write

# ls Docker  | jq  --raw-input .  | jq --slurp .

jobs:
    pre:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            # - name: Setup matrix
            #   run: |
            #     echo "docker_files=$(ls Docker  | jq  --raw-input .  | jq --slurp .)" >> "$GITHUB_ENV"
            - id: set-matrix
              run: |
                echo "::set-output name=docker_files::$(ls Docker  | jq  --raw-input .  | jq --slurp .)"
        outputs:
            docker_files: ${{steps.set-matrix.outputs.docker_files}}
    
    test:
        needs: pre
        runs-on: ubuntu-latest
        strategy:
            matrix:
                docker_files: ${{fromJson(needs.pre.outputs.docker_files)}}
        steps:
            - run: |
                echo ${{matrix.docker_files}}
